package day0326;

import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;

public class Ex15_FileException {

	static final String FILENAME = "/Users/parkminji/Documents/naver_0314/workall/memo1.txt";
	static final String FILENAME2 = "/Users/parkminji/Documents/naver_0314/workall/memo2.txt";

	
	static public void fileSave() {
		
		FileWriter fw = null;
		try {
			fw = new FileWriter(FILENAME);
			fw.write("이름 : 홍길동\n");
			fw.write("나이 : 20세 \n");
			fw.write("주소 : 강남구\n");
			System.out.println("파일을 확인하세요 !");
			
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} finally {
			try {
				fw.close();
			} catch (IOException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		}
		
	}
	
	static public void fileSave2() throws IOException {
		
		Scanner sc = new Scanner(System.in);
		String name, hp, addr;
		while(true) {
			FileWriter fw = null;
			fw = new FileWriter(FILENAME2, true);
		}
		
	}
	public static void main(String[] args) {
		// TODO Auto-generated method stub

//		fileSave();
		try {
			fileSave2();

		}catch (IOException e) {
			e.printStackTrace();
		}

	}

}
